### PR TITLE
Enable reading variables from files as well (docker/rancher secrets)

### LINKED ISSUE #26: Reading environment variables from file
While using rancher secrets, data to pass into environment variables are mounted in a file on `/run/secrets`. Some images on docker hub like `mysql` supports this kind of variable passing, e.g. you pass an environment variable `MYSQL_USERNAME_FILE=/run/secrets/MYSQL_USERNAME` and on entrypoint it read the environment variable from that file. Is it possible to get the same behaviour with this image?

Relevant part from rancher docs: http://rancher.com/docs/rancher/latest/en/cattle/secrets/#docker-hub-images

And this is an example entrypoint that reads environment variables from files (see`file_env` function): 
https://github.com/docker-library/mysql/blob/0590e4efd2b31ec794383f084d419dea9bc752c4/5.7/docker-entrypoint.sh#L25

### PR DESCRIPTION
**Pull request by th0th**
(Closes #26)

Used the same `file_env` function from mysql image's entrypoint (https://github.com/docker-library/mysql/blob/0590e4efd2b31ec794383f084d419dea9bc752c4/5.7/docker-entrypoint.sh#L25).

### CODE REVIEW

**Comment by deitch** [comment]
Nice. I like it.

1. Can you rebase, as it is out of date?
2. Can you add the other env vars?
3. Please update the README as to how to use it.

Thanks!

**Comment by th0th** [comment]
1. Rebased.
2. I added variables, hope I didn't miss any.
3. Added a part about the usage of files for environment variables.

**Comment by deitch** [comment]
No argument about `DB_SERVER` vs `DBSERVER`, but we probably should have kept it as separate PRs. Leave for now though.

Now, why is CI failing?

**Comment by deitch** [comment]
Ah. You changed `DBSERVER` to`DB_SERVER` but not in the tests. See https://github.com/deitch/mysql-backup/blob/master/test/test.sh#L72

**Comment by th0th** [comment]
You are right, variable name change should have been in a separate PR. Sorry, it looked like a good idea to include in this PR while changing :) BTW, I updated `test.sh`.

**Comment by deitch** [comment]
Looks better now. Would be nice if we had env`_FILE` tests, too, but not going to overdo it.

In any case, this needs a rebase before it can be merged in, but CI passes. Rebase, green CI, then we can do it.

**Comment by jacksgt** [comment]
Hey, I think this is a cool and useful addition, could you have a look at the PR again? @th0th

**Comment by th0th** [comment]
@jacksgt I am not very familiar with tests of this kind. Do you want to help?

**Comment by jacksgt** [comment]
I think deitch was fine with not having tests right now.

**Comment by deitch** [comment]
What @jacksgt said. No need for additional tests at this point, is more than fine. And you fixed the failing error. Just needs to be rebased.

**Comment by deitch** [comment]
> Any idea what might be wrong?

With ~4000 lines of output, almost anything! LOL!

I will look and see.

**Comment by deitch** [comment]
Looks like the pre-backup scripts didn't run or lost output:

```
+echo 'Passed: 14'
Passed: 14
+echo 'Failed: 7'
Failed: 7
+[[ 7 != \0 ]]
+(( i=0 ))
+(( i< 7 ))
+echo '0:  /backups/SEQ/data Pre-backup script didn'\''t run, output file doesn'\''t exist'
0:  /backups/SEQ/data Pre-backup script didn't run, output file doesn't exist
+(( i++ ))
+(( i< 7 ))
+echo '1:  file:///backups/SEQ/data Pre-backup script didn'\''t run, output file doesn'\''t exist'
1:  file:///backups/SEQ/data Pre-backup script didn't run, output file doesn't exist
+(( i++ ))
+(( i< 7 ))
+echo '2:  smb://smb/noauth/SEQ/data Pre-backup script didn'\''t run, output file doesn'\''t exist'
2:  smb://smb/noauth/SEQ/data Pre-backup script didn't run, output file doesn't exist
+(( i++ ))
+(( i< 7 ))
+echo '3:  smb://smb/nopath Pre-backup script didn'\''t run, output file doesn'\''t exist'
3:  smb://smb/nopath Pre-backup script didn't run, output file doesn't exist
+(( i++ ))
+(( i< 7 ))
+echo '4:  smb://user:pass@smb/auth/SEQ/data Pre-backup script didn'\''t run, output file doesn'\''t exist'
4:  smb://user:pass@smb/auth/SEQ/data Pre-backup script didn't run, output file doesn't exist
+(( i++ ))
+(( i< 7 ))
+echo '5:  smb://CONF;user:pass@smb/auth/SEQ/data Pre-backup script didn'\''t run, output file doesn'\''t exist'
5:  smb://CONF;user:pass@smb/auth/SEQ/data Pre-backup script didn't run, output file doesn't exist
+(( i++ ))
+(( i< 7 ))
+echo '6:  s3://mybucket/SEQ/data Pre-backup script didn'\''t run, output file doesn'\''t exist'
6:  s3://mybucket/SEQ/data Pre-backup script didn't run, output file doesn't exist
+(( i++ ))
+(( i< 7 ))
+exit 1
make: *** [test] Error 1
```

**Comment by deitch** [comment]
[Here](https://github.com/deitch/mysql-backup/pull/29/files#diff-b8765e8e12fe5b90ee3f4f3a864b5d96R75) Looks like you changed the mapping of `-v /tmp/backups/${seqno}/:/scripts.d/` to `-v /tmp/backups/${seqno}/post-backup:/scripts.d/post-backup` which (I believe) made the test runner unable to find the pre-backup outputs. Why the change?

**Comment by th0th** [comment]
@deitch sorry, the change was not intentional. I think it slipped out when I was rebasing.

**Comment by deitch** [comment]
> sorry, the change was not intentional

All part of the fun!

**Comment by th0th** [comment]
Thanks!

**Comment by deitch** [comment]
I really need to get CI to automate the pushes for me, not just the tests. I do it with all of the enterprise client deployments. But for now, `make push` I go...

**Comment by deitch** [comment]
`deitch/mysql-backup:9c5a5e0a41ce269abc3ab776feebd5576ecefc5f`

I would love to redo the whole thing in go, it would be 1/4 the image size. But this is volunteer OSS, all question of time.

**Comment by jacksgt** [comment]
Awesome!

**Pull request merged**
